<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0YIIPmO\srcApp_KernelENVDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0YIIPmO/srcApp_KernelENVDebugContainer.php') {
    touch(__DIR__.'/Container0YIIPmO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelENVDebugContainer::class, false)) {
    \class_alias(\Container0YIIPmO\srcApp_KernelENVDebugContainer::class, srcApp_KernelENVDebugContainer::class, false);
}

return new \Container0YIIPmO\srcApp_KernelENVDebugContainer([
    'container.build_hash' => '0YIIPmO',
    'container.build_id' => '3609b6f7',
    'container.build_time' => 1590708658,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0YIIPmO');
