<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerARzgu2P\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerARzgu2P/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerARzgu2P.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerARzgu2P\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerARzgu2P\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'ARzgu2P',
    'container.build_id' => '990c297a',
    'container.build_time' => 1590712136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerARzgu2P');
