<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxdjQ0K\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxdjQ0K/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCxdjQ0K.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCxdjQ0K\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerCxdjQ0K\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'CxdjQ0K',
    'container.build_id' => 'fc73f103',
    'container.build_time' => 1591369659,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxdjQ0K');
