<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6RFlKxh\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6RFlKxh/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container6RFlKxh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container6RFlKxh\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container6RFlKxh\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '6RFlKxh',
    'container.build_id' => 'af6e41e7',
    'container.build_time' => 1592345177,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6RFlKxh');
