<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'basket' => [[], ['_controller' => 'App\\Controller\\BasketController::show'], [], [['text', '/basket']], [], []],
    'basket.add' => [['id'], ['_controller' => 'App\\Controller\\BasketController::add'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/add']], [], []],
    'basket.remove' => [['id'], ['_controller' => 'App\\Controller\\BasketController::remove'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/remove']], [], []],
    'basket.clear' => [[], ['_controller' => 'App\\Controller\\BasketController::clear'], [], [['text', '/clear']], [], []],
    'product.index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product']], [], []],
    'product.show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/product/show']], [], []],
];
