<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVYcPg6u\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVYcPg6u/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVYcPg6u.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVYcPg6u\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVYcPg6u\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VYcPg6u',
    'container.build_id' => 'e5074f03',
    'container.build_time' => 1590960496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVYcPg6u');
