<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR5mCDs7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR5mCDs7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR5mCDs7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR5mCDs7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR5mCDs7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R5mCDs7',
    'container.build_id' => 'b98c2eb2',
    'container.build_time' => 1589747230,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR5mCDs7');
