<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKrHQex\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKrHQex/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNKrHQex.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNKrHQex\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNKrHQex\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NKrHQex',
    'container.build_id' => '71954a3e',
    'container.build_time' => 1591565269,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKrHQex');
